### PR TITLE
[WIP] Go mobile-first

### PR DESCRIPTION
**Pull request by ricardoduplos**
Toggle show/hide menu functionality still missing on small screens. @scisco Do you have some time to tackle this part?

### CODE REVIEW

**Comment by scisco** [comment]
@ricardomestre I'll work on it. thanks.

**Comment by scisco** [comment]
@ricardomestre I didn't get the chance to fix the button. If you can finish it, it'd be great

**Review by scisco — APPROVED** [review]
@ricardomestre excellent

**Comment by ricardoduplos** [comment]
I noticed a few bugs that I still have to fix. Will work on these tomorrow.

**Comment by scisco** [comment]
thanks.

**Pull request merged**
